### ISSUE TITLE
Kudos number does not appears

### ISSUE THREAD

**Issue by Rizqyfm** [kudokuapp/kudoku.id#2]
![Screenshot 2022-11-25 at 09 08 07](https://user-images.githubusercontent.com/84706087/203886038-cf51bf18-4ce4-48d8-bf5d-3e1c86a6cd7f.png)

**Comment by AldiMegantaraA** [comment]
doneee

**Comment by Rizqyfm** [comment]
Thanks @AldiMegantaraA !
